---
title: "R Notebook"
author: daniel
date: 28/09/2020
output: html_notebook
---

# Identification of Outliers
```{r}
root_path <- "/Users/daniel/LocalFiles for TFM/"
setwd(root_path)
filePath <- paste0(root_path,"youtubeProjectTFM/src/sentiment_analysis.csv")
sentAnalysis <- read.csv(filePath,sep=",",header = T)

summary(sentAnalysis)
```
```{r}
beauty_fitness <- read.delim(paste0(root_path,"Files/Beauty_Fitness.txt"),header=FALSE,sep=" ",dec=" ")
books_literature <- read.delim(paste0(root_path,"Files/Books_Literature.txt"),header=FALSE,sep=" ",dec=" ")
business_industrial <- read.delim(paste0(root_path,"Files/Business_Industrial.txt"),header=FALSE,sep=" ",dec=" ")
computers_electronics <- read.delim(paste0(root_path,"Files/Computers_Electronics.txt"),header=FALSE,sep=" ",dec=" ")
food_drink <- read.delim(paste0(root_path,"Files/Food_Drink.txt"),header=FALSE,sep=" ",dec=" ")
```

```{r}
library(dplyr)
sentAnalysis <- sentAnalysis %>% mutate(category=ifelse(video_id %in% beauty_fitness$V1,paste("Beauty and Fitness"),category)) %>%
    mutate(category=ifelse(video_id %in% books_literature$V1,paste("Books and Literature"),category)) %>%
    mutate(category=ifelse(video_id %in% business_industrial$V1,paste("Business and Industrial"),category)) %>%
    mutate(category=ifelse(video_id %in% computers_electronics$V1,paste("Computers and Electronics"),category)) %>%
    mutate(category=ifelse(video_id %in% food_drink$V1,paste("Food and Drink"),category)) %>%
  filter(category != "NA")

nrow(sentAnalysis[sentAnalysis$category=="NA",])
nrow(sentAnalysis[sentAnalysis$category=="Beauty and Fitness",])
nrow(sentAnalysis[sentAnalysis$category=="Books and Literature",])
nrow(sentAnalysis[sentAnalysis$category=="Business and Industrial",])
nrow(sentAnalysis[sentAnalysis$category=="Computers and Electronics",])
nrow(sentAnalysis[sentAnalysis$category=="Food and Drink",])

write.csv(sentAnalysis,"sentiment-analysis-analytics.csv",row.names = FALSE)
```

# Boxplot
```{r}
boxplot(sentAnalysis$negative_comments,sentAnalysis$neutral_comments,sentAnalysis$positive_comments, names = c("Negative","Neutral","Positive"),las = 2, col = c("royalblue","lightgreen","orange"))
mtext("Comment Sentiment", side = 1, line = 4)
mtext("Number of Comments", side = 2, line = 3)
```
```{r}
#Positive comments
Q1 <- summary(sentAnalysis$positive_comments)[2]
Q3 <- summary(sentAnalysis$positive_comments)[5]
IQR_POS_COM <- Q3 - Q1
IQR_POS_COM

#Negative comments
Q1 <- summary(sentAnalysis$neutral_comments)[2]
Q3 <- summary(sentAnalysis$neutral_comments)[5]
IQR_NEU_COM <- Q3 - Q1
IQR_NEU_COM

#Neutral comments
Q1 <- summary(sentAnalysis$negative_comments)[2]
Q3 <- summary(sentAnalysis$negative_comments)[5]
IQR_NEG_COM <- Q3 - Q1
IQR_NEG_COM
```
```{r}
#Detecting potential outliers
outliers_pos <- boxplot.stats(sentAnalysis$positive_comments)$out
outliers_neg <- boxplot.stats(sentAnalysis$negative_comments)$out
outliers_neu <- boxplot.stats(sentAnalysis$neutral_comments)$out

cat("Potential outliers for positive comments: ",length(outliers_pos))
cat("\n")
cat("Potential outliers for negative comments: ", length(outliers_neg))
cat("\n")
cat("Potential outliers for neutral comments: ", length(outliers_neu))
```